# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy source files
COPY pyproject.toml README.md server.py ./

# Install MCP CLI, boto3, and our package
RUN pip install --no-cache-dir mcp[cli] boto3 && \
    pip install --no-cache-dir .

# Default entrypoint: use MCP CLI to run the server on stdio
ENTRYPOINT ["mcp", "run", "server.py"]
